---
name: Rust

"on":
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies (Ubuntu)
        run: sudo apt install clang llvm pkg-config nettle-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install dependencies (macOS)
        run: |
          brew install nettle@3
          echo "PKG_CONFIG_PATH=$(brew --prefix nettle@3)/lib/pkgconfig" >> "$GITHUB_ENV"
        if: matrix.os == 'macos-latest'
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Build (no features)
        run: cargo build --workspace --no-default-features
        env:
          RUSTFLAGS: -Dwarnings
      - name: Build (default features)
        run: cargo build --workspace
        env:
          RUSTFLAGS: -Dwarnings
      - name: Build (all features)
        run: cargo build --workspace --all-features
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (no features)
        run: cargo test --workspace --no-default-features
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (default features)
        run: cargo test --workspace
        env:
          RUSTFLAGS: -Dwarnings
      - name: Test (all features)
        run: cargo test --workspace --all-features
        env:
          RUSTFLAGS: -Dwarnings

  minimal-versions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Install cargo-minimal-versions and cargo-hack
        run: cargo install cargo-minimal-versions cargo-hack
      - name: Test with minimal versions
        run: cargo minimal-versions test --workspace
